// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$Rebolt = require("rebolt/src/components/text.js");
var View$Rebolt = require("rebolt/src/components/view.js");
var Style$Rebolt = require("rebolt/src/style.js");

var currentDay = new Date().getDay() | 0;

function getGainz(day) {
  if (day > 6 || day < 0) {
    return "Guess you're doing everything here in the post-week future";
  } else {
    switch (day) {
      case 0 : 
          return "Whatever. Yoga maybe?";
      case 1 : 
      case 4 : 
          return "CHEST DAY";
      case 2 : 
      case 5 : 
          return "ARM DAY";
      case 3 : 
      case 6 : 
          return "BACK DAY";
      
    }
  }
}

function app() {
  return ReasonReact.element(/* None */0, /* None */0, View$Rebolt.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$Rebolt.style(/* :: */[
                          Style$Rebolt.flexDirection(/* Column */2),
                          /* :: */[
                            Style$Rebolt.alignItems(/* Center */2),
                            /* :: */[
                              Style$Rebolt.justifyContent(/* Center */2),
                              /* :: */[
                                Style$Rebolt.flex(1),
                                /* [] */0
                              ]
                            ]
                          ]
                        ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                  ReasonReact.element(/* None */0, /* None */0, Text$Rebolt.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$Rebolt.style(/* :: */[
                                  Style$Rebolt.fontSize(/* Float */Block.__(0, [32])),
                                  /* [] */0
                                ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Today is"])),
                  ReasonReact.element(/* None */0, /* None */0, Text$Rebolt.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$Rebolt.style(/* :: */[
                                  Style$Rebolt.fontSize(/* Float */Block.__(0, [48])),
                                  /* [] */0
                                ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[getGainz(currentDay)]))
                ]));
}

exports.currentDay = currentDay;
exports.getGainz = getGainz;
exports.app = app;
/* currentDay Not a pure module */
